export const profile = {
  name: "Yash Wardhan",
  title: "Developer / Life Long Learner",
  // headline: "Seeking Full-time roles",
  // headline: "I develop code.",
  headlineStart: "I",
  headlineList: [
    // "code with passion.",
    // "dream big.",
    // "learn endlessly.",
    // "design solutions.",
    // // "craft experiences.",
    // "imagine possibilities.",
    // "embrace innovation.",
    // // "shape the future.",
    // "push boundaries.",
    // "aspire for excellence.",
    // // "inspire action.",
    // // "seek growth.",
    // // "value creativity.",
    // // "analyze systems.",
    // "innovate constantly.",
    // // "think deeply.",
    // "turn ideas into reality.",
    // // "redefine limits.",

    // // "build projects.",
    // // "enjoy challenges.",
    // // "explore new things.",
    // // "like technology.",
    // // "solve problems.",

    // "empower innovation.",
    "craft solutions, not just code.",
    // "redefine what's possible.",
    "try to push the envelope of technology.",
    "aim to transform ideas into impact.",
    // "fuel creative growth.",
    // "challenge the norm.",
    // "curate the future.",
    "code with clarity.",
    "aspire to build beyond boundaries.",
    "simplify the complex.",
    // "empathize, then innovate.",
    "design with intent.",
    // "lead with creativity.",
    "think outside the algorithm.",
    "want to create with purpose.",
    "aim to solve with precision.",
    // "shape the digital landscape.",
    "try to master complexity, deliver simplicity.",
    // "pioneer new paradigms."
  ],

  description: [
    "Aspiring Software Engineer passionate about leveraging technology to solve complex problems and drive innovation. I have master’s degree in Computer Science from Rutgers University–New Brunswick, where I strengthened my expertise in core computer science principles and explored diverse fields, including Cloud, Artificial Intelligence, Networking, and Software Testing.",
    "A lifelong learner and problem-solver, I’m passionate about staying ahead of technological trends and contributing to impactful, innovative projects. Let’s connect to discuss ideas, opportunities, and exciting ventures in technology!",
  ],

  resumeUrl:
    "https://drive.google.com/file/d/1Vu5hhBX__ankyiL24D57fhVOQ73c0V-i/view?usp=drive_link",
  mailId: "yashwardhan2210@gmail.com",
  toolsFocus: ["react", "aws", "docker", "python", "git", "c++"],

  education: [
    {
      name: "Rutgers, The State University of New Jersey",
      location: "New Brunswick, NJ",
      startMonth: "September",
      startYear: "2022",
      current: false,
      endMonth: "May",
      endYear: "2024",
      degree: "Master of Science",
      course: "Computer Science",
      gpa: 3.8,
      maxGpa: 4,
      subjects: [
        "Computer Networks",
        "Adv Topics: Statistics for Machine Learning",
        "Topics In Computers In Biomedicine",
        "Business Intelligence with Visual Analytics",
        "Advanced Robotics",
        "Programming Finance",
        "Mathematical Foundations of Data Science",
        "Natural Language Processing",
        "Introduction To Artificial Intelligence",
        "Data Structures and Algorithms",
        "Operating Systems Design",
        "Database Management Systems",
      ],
      description: [],
      icon: "/logos/rutgers.png",
      url: "https://www.linkedin.com/school/rutgersnb/",
      transcript:
        "https://drive.google.com/file/d/1EYT_D3Bbo38-fuNdUW47yw8Pb-m0KWbq/view?usp=drive_link",
    },
    {
      name: "Manipal Institute of Technology ",
      location: "Manipal, India",
      startMonth: "July",
      startYear: "2018",
      current: false,
      endMonth: "June",
      endYear: "2022",
      degree: "Bachelor of Technology",
      course: "Information Technology",
      gpa: 8.7,
      maxGpa: 10,
      subjects: [
        "Semantic Web",
        "Cloud Computing",
        "Internet of Things",
        "Neural Networks and Fuzzy Logic",
        "Machine Learning for Data Analytics",

        "Data Warehousing and Data Mining",
        "Distributed Systems",
        "Big Data Analytics",
        "Information Retrieval",

        "Cyber Security",
        "Embedded Systems",
        "Database Systems",
        // "Software Engineering",
        "Enterprise Data Architecture",

        "Computer Network Protocols",
        "Computer Organization and Microprocessor Systems",
        // "Design and Analysis of Algorithms",
        // "Operating Systems",
        "Sensor Technology",

        // "Data Structures",
        "Digital Systems",
        "Object Oriented Programming",
        "Principles of Data Communication",
        "Engineering Mathematics",

        // "Mechanics of Solids",
        // "Basic Electronics",
        // "Communication Skills in English",
        // "Basic Mechanical Engineering",
        // "Engineering Physics",

        // "Biology for Engineers",
        // "Engineering Chemistry",
        // "Environmental Studies",
        // "Problem Solving Using Computers",
        // "Basic Electrical Technology",
        // "Engineering Graphics",
      ],
      description: [],
      icon: "/logos/manipal.png",
      url: "https://www.linkedin.com/school/manipal-institute-of-technology/",
      transcript:
        "https://drive.google.com/file/d/1LZSZ9B7D8MDsevld3d0Z2-WXN-PzAqmk/view?usp=drive_link",
    },
  ],
  experiences: [],
  internships: [
    {
      company: "Acts Retirement-Life Communities",
      location: "Fort Washington, PA",
      role: "Data Science Intern",
      startMonth: "June",
      startYear: "2023",
      current: false,
      endMonth: "August",
      endYear: "2023",
      description: [
        "Optimized T-SQL procedures to streamline data pipelines, enhancing quality of business intelligence and reporting.",
        "Collaborated with teams to gather data requirements and deliver analytical solutions to meet business needs.",
        "Designed Power BI dashboards, providing real-time insights into performance metrics to support data-driven decision-making.",
      ],
      icon: "/logos/acts.png",
      url: "https://www.linkedin.com/company/actsretirement/",
      stack: [
        "MS SQL Server",
        "Power BI",
        "DAX",
        "T-SQL",
        "Jira",
        "Agile Methodologies",
        "MS Power Query",
      ],
    },
    {
      company: "RTWO Healthcare Solutions",
      location: "Bangalore, India",
      role: "Software Engineer Intern",
      startMonth: "January",
      startYear: "2022",
      current: false,
      endMonth: "May",
      endYear: "2022",
      description: [
        "Developed a full-stack IoT application to manage admission and automate equipment allocation, improving operational efficiency.",
        "Engineered embedded systems with microcontrollers and integrated RFID technology for automated equipment assignment, improving efficiency and reducing manual errors.",
        "Developed and implemented RESTful API endpoints for real-time equipment tracking and scanner integration, ensuring a robust and maintainable backend architecture.",
      ],
      icon: "/logos/rtwo.png",
      url: "https://www.linkedin.com/company/rtwo-healthcare-solutions/",
      stack: [
        "React",
        "Node.js",
        "C",
        "Arduino",
        "MERN",
        "Express.js",
        "MongoDB",
        "REST APIs",
      ],
    },
  ],
  projects: [
    {
      title: "Real-Time Sports Data Stream",
      startMonth: "December",
      startYear: "2024",
      current: true,
      endMonth: "January",
      endYear: "2025",
      description: [
        "Developed a distributed real-time sports data processing system ensuring seamless communication between containers through an event-driven architecture.",
        "Engineered a Kafka message broker to handle high-throughput data streams and integrated with PostgreSQL for efficient data storage, creating a producer-consumer system to process and deliver live match updates.",
        "Built a full-stack application with React and Express.js, utilizing Docker Compose for container orchestration, providing a scalable, modular, and efficient architecture for real-time data visualization and processing.",
      ],
      icon: "/projects/sports.png",
      url: "https://github.com/yashw22/real-time-sports-data-stream",
      stack: [
        "Kafka",
        "Docker",
        "PostgreSQL",
        "Node.js",
        "Express.js",
        "React",
      ],
    },
    {
      title: "Deck Detective Card Game",
      startMonth: "November",
      startYear: "2024",
      current: false,
      endMonth: "December",
      endYear: "2024",
      description: [
        "Engineered a decentralized, peer-to-peer, turn-based multiplayer game using React, PeerJS, and WebRTC for real-time communication, ensuring seamless player interaction with minimal server-side dependencies.",
        "Developed robust game logic algorithms for managing multiple JSON data exchanges, handling edge cases, and facilitating dynamic interactions in a peer-to-peer environment.",
        "Deployed the game on GitHub Pages, enabling players to run the game locally, with a server used solely for peer discovery.",
      ],
      icon: "/projects/dd.jpg",
      url: "https://github.com/yashw22/deck-detective",
      stack: ["React", "Tailwind", "PeerJS", "JavaScript", "GitHub Pages", "Git", "WebRTC"],
    },
    {
      title: "Robot Navigation using Reinforcement Learning",
      startMonth: "September",
      startYear: "2023",
      current: false,
      endMonth: "December",
      endYear: "2023",
      description: [
        "Trained a neural network using model-free reinforcement learning to enable Unitree Go1 robot to navigate autonomously and avoid obstacles in complex environments within the Isaac Gym Simulator.",
      ],
      icon: "/projects/rl.gif",
      url: "https://github.com/yashw22/go1_gym_simulation",
      stack: [
        "Reinforcement Learning",
        "PyTorch",
        "Python",
        "Isaac Gym",
        "NumPy",
      ],
    },
    {
      title: "Tweet Search Application",
      startMonth: "March",
      startYear: "2023",
      current: false,
      endMonth: "April",
      endYear: "2023",
      description: [
        "Developed a Flask-based search application that enables users to perform keyword and filter-based searches on tweets.",
        "Implemented a local caching mechanism, drastically reducing response times for subsequent queries, optimizing performance.",
      ],
      icon: null,
      url: "https://github.com/yashw22/TwitterDB",
      stack: ["Python", "MongoDB", "MySQL", "Flask", "REST APIs", "SQL"],
    },
    {
      title: "Visualizing AES Functions in Python",
      startMonth: "October",
      startYear: "2022",
      current: false,
      endMonth: "November",
      endYear: "2022",
      description: [
        "Implemented AES encryption and decryption algorithms, replicating the four core operations (SubBytes, ShiftRows, MixColumns, AddRoundKey) and their corresponding inverses for each AES round, using user-specified keys and parameters.",
        "Developed interactive prompts to allow users to visualize the step-by-step execution of each AES operation, enhancing understanding of the cryptographic process.",
      ],
      icon: null,
      url: null,
      stack: ["Python", "AES"],
    },
    {
      title: "Real-time Face Mask Detection",
      startMonth: "June",
      startYear: "2021",
      current: false,
      endMonth: "June",
      endYear: "2021",
      description: [
        "Developed an image recognition model using YOLOv3 to identify individuals not wearing face masks in real-time.",
        "Leveraged transfer learning by fine-tuning pre-trained parameters with a customized dataset for enhanced accuracy.",
      ],
      icon: null,
      url: "https://github.com/yashw22/FaceMask-Detection",
      stack: ["OpenCV", "YOLO", "TensorFlow", "Python"],
    },
    {
      title: "Travel Journal",
      startMonth: "February",
      startYear: "2021",
      current: false,
      endMonth: "June",
      endYear: "2021",
      description: [
        "Developed a cross-platform social media application that allows users to share travel experiences and interact with others' posts.",
        "Designed and implemented distinct mobile and web platforms to deliver a seamless and tailored user experience for each medium.",
      ],
      icon: null,
      url: "https://github.com/yashw22/TravelJournal-FrontEnd",
      stack: ["Android Studio", "Node.js", "Java", "JavaScript", "XML", "JSON"],
    },
    {
      title: "Project Autonomous Underwater Vehicle Manipal",
      startMonth: "August",
      startYear: "2019",
      current: false,
      endMonth: "May",
      endYear: "2021",
      description: [
        "Leveraged Robot Operating System to enable seamless communication among AUV components, improving system efficiency and data exchange for task completion.",
        "Collaborated in a cross-functional team to develop a model to detect and classify objects in real-time, using CNN and YOLO."
      ],
      icon: null,
      url: "https://www.projectauvm.com/",
      stack: ["ROS", "TensorFlow", "CNN", "OpenCV", "YOLO", "Python", "C++"],
    },
  ],
  certifications: [
    {
      title: "Design Patterns in Java",
      source: "Udemy",
      issueMonth: "December",
      issueYear: "2024",
      description: [],
      icon: "/certs/designpatterns.jpg",
      url: "https://www.ude.my/UC-0eaa2afd-2c89-4331-a5a1-c4a99eec452c/",
    },
    {
      title: "Selenium WebDriver with Java",
      source: "Udemy",
      issueMonth: "December",
      issueYear: "2024",
      description: [],
      icon: "/certs/selenium.jpg",
      url: "https://www.ude.my/UC-baae7bc0-fd91-4f10-a00b-3ea0b280f1f1/",
    },
    {
      title: "Full-Stack Web Development with React",
      source: "Coursera",
      issueMonth: "July",
      issueYear: "2021",
      description: [],
      icon: "/certs/mern.png",
      url: "https://coursera.org/share/b26831f21777933532564e9a733a25fa",
    },
    {
      title: "Deep Learning by DeepLearning.AI",
      source: "Coursera",
      issueMonth: "May",
      issueYear: "2020",
      description: [],
      icon: "/certs/deeplearning.png",
      url: "https://coursera.org/share/28f1af3b51ccdd16584aa97e663941af",
    },
  ],
  links: [
    {
      name: "Mail",
      icon: null,
      url: "mailto:yashwardhan2210@gmail.com",
      handle: "yashwardhan2210@gmail.com",
    },
    {
      name: "Linkedin",
      icon: null,
      url: "https://www.linkedin.com/in/yashw22/",
      handle: "linkedin.com/in/yashw22",
    },
    {
      name: "Github",
      icon: null,
      url: "https://github.com/yashw22",
      handle: "github.com/yashw22",
    },
    // {
    //   name: "Instagram",
    //   icon: null,
    //   url: null,
    // }
  ],
};
